### ISSUE TITLE
Short Reverbs make sounds too loud

### ISSUE THREAD

**Issue by YurgenSchn** [thedocruby/resounding#41]
I think that reverbs beign added on top of source sounds in small spaces actually makes the combined sound distinctively loud. Definitely noticeable in small caves, the old gen ones. I don't feel like it's as intrusive of a problem in big spaces.

If lowering the source-sound volume is possible, maybe lowering it for short (intense) reverbs could do the trick.

**Comment by thedocruby** [comment]
This is a good idea, and definitely a possibility! Thanks for your feedback! :)

**Comment by YurgenSchn** [comment]
By trying the Milestone Alpha v2 (bc.6), i got to test this it without reverbs and absorption.

Basically, i set reverb volume to 0.0, the reverb and absorption brightness to 20.0 (currently, it doesnt make it brighter, but removes any muffling), and also set to 0.0 the air/humidity absorption settings.

In places where there would be reverb, short or long ones, the source sound was noticeably louder than in places where it was absorbed (like in a small wool chamber). Maybe it's not the source sound itself being louder, but the addition/composition of the "reverb-and-absorption-less source clone" (even if, weirdly, reverb volume is set to 0).

I still believe the problem is the same, and i guess still can be treated as a future enhancement.

**Comment by YurgenSchn** [comment]
Actually, it seems to be related to issue #50, and how the airspace detection works: even without reverb and absorption effects, the wool chamber test still shows that by playing a jukebox at the opening of the wool chamber, it will be quieter inside, and quieter as i go in, further from the opening (as if it's beign played outside, in another envinronment)

At this point, i'd go as far as to say its **not** the reverb increasing volume of source sounds - as i mentioned before, the "composite sound" beign louder. I believe its completely related to the airspace detection/occlusion problem.
