### ISSUE TITLE
Worlds fails to load, "Loading Terrain...", with Bobby installed

### ISSUE THREAD

**Issue by giorov** [thedocruby/resounding#55]
Worlds fails to load, "Loading Terrain...", with these mods:

bobby-3.1.1.jar
resounding-1.0.0-bc.8.jar
cloth-api-3.2.64.jar
cloth-config-6.2.57-fabric.jar
iris-mc1.18.2-1.2.2-build.32.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar

Removing Resounding circumvents the error.

**Comment by thedocruby** [comment]
This is likely only because Resounding does not have a version for 1.18.2. Make sure to check version numbers before downloading a mod.
