### ISSUE TITLE
Performance Hungry - Crashes

### ISSUE THREAD

**Issue by SlamTheDragon** [thedocruby/resounding#57]
**Description**
The mod itself is performance hungry by in its default settings (Slowed down chunk loading behavior and a lot of noticable frame drops). Sound Physics Fabric (The previous version of this mod) however does the same thing but the odds of it crashing are expected to be really low. Frame drops however are somewhat noticable.

**To Reproduce**
1. Enter a world
2. Play Minecraft normally

**Expected behavior**
A smooth playthrough similar to Sound Physics Remastered (https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered).

**My Machine:**
 - OS: Windows
 - Minecraft Version: 1.18.2
 - Mod version: Milestone Alpha 1.3 (for 1.18.2), Version number: v1.0.0-bc.9, Version ID n6x015i9
 (Extra: i7 9th gen, NVidia 1660ti)

 - Sound Card:
Realtek(R) Audio
NVidia Virtual Audio Device (Wave Extensible) (WDM)
NVidia High Definition Audio
Intel(R) Display Audio

 - Mods list:
Bedrockify
cloth-config
continuity
dynamic-fps
entityculling-fabric
fabric-api
freecam
iris
lambdynamiclights
modmenu
okzoomer
replaymod
**resounding**
sodium-extra
sodium-fabric

**Additional context**
Raytraced debugging Completely obliterates the rendering engine (that was an attempt)

**Crash Report/Logs**
https://pastebin.com/iyv42vVM

I'd hope y'all can get around with the optimization needed for this mod

**Comment by mikenrafter** [comment]
Could you profile this with [Spark](https://spark.lucko.me/)? Knowing where this issue stems from could help diagnose the issue.

**Comment by SlamTheDragon** [comment]
I may have forgotten about this but I also did not read the text not to test the path tracing visibility feature to an ordinary Minecraft world for it will _totally lag the client out_. Something along those lines. Will close the issue now. Sorry for the wait!

Edit: That was what I was trying to explain before (I confused myself), I have the settings properly configured to meet the standards of my PC so that I won't get stuttery frames (in both debugging and normal playtimes).
